"""DuckBot navigation configuration — tune these values for your setup."""

PERIMETER_WIDTH_CM = 1000
PERIMETER_HEIGHT_CM = 200
PERIMETER_CM = [
    (0, 0),
    (PERIMETER_WIDTH_CM, 0),
    (PERIMETER_WIDTH_CM, PERIMETER_HEIGHT_CM),
    (0, PERIMETER_HEIGHT_CM),
]

START_X_CM = 30
START_Y_CM = 100
START_HEADING_RAD = 0.0

END_X_CM = 960
END_Y_CM = 100

SONAR_TRIG = 23
SONAR_ECHO = 24
SONAR2_TRIG = 17
SONAR2_ECHO = 27

SONAR_BLIND_ZONE_CM = 20
DUCK_RADIUS_CM = 15


def compute_obstacle_threshold(cfg):
    reaction_cm = (cfg["EXPLORE_SPEED"] * cfg["MAX_SPEED_CM_S"]) / cfg["LOOP_HZ"]
    distance_cm = SONAR_BLIND_ZONE_CM + 3 + reaction_cm
    return max(25, round(distance_cm))


BRAIN_CFG = {
    "PERIMETER_MARGIN_CM": 30,
    "EXPLORE_SPEED": 0.4,
    "TURN_SPEED": 0.5,
    "SCAN_SPEED": 0.4,
    "AVOID_COOLDOWN_TIME": 0.5,
    "AVOID_CLEAR_THRESHOLD_CM": 100,
    "AVOID_MAX_SCAN_RAD": 1.57,
    "AVOID_REACTIVE_KP": 0.003,
    "AVOID_TARGET_DIST_CM": 30,
    "AVOID_REACTIVE_FWD_SPEED": 0.3,
    "AVOID_REACTIVE_TIMEOUT": 30.0,
    "GOAL_X": END_X_CM,
    "GOAL_Y": END_Y_CM,
    "STUCK_THRESHOLD_COUNT": 3,
    "STUCK_WINDOW_TIME": 10.0,
    "STUCK_ESCAPE_TIME": 2.0,
    "MAX_SPEED_CM_S": 100,
    "WHEEL_BASE_CM": 30,
    "HEADING_TOLERANCE_RAD": 0.26,
    "EXPLORE_JITTER_TIME": 6.0,
    "EXPLORE_JITTER_AMOUNT": 0.10,
    "SONAR_FAIL_THRESHOLD": 5,
    "SONAR_FAIL_SPEED_SCALE": 0.3,
    "LOOP_HZ": 20,
}
BRAIN_CFG["OBSTACLE_THRESHOLD_CM"] = compute_obstacle_threshold(BRAIN_CFG)

# --- Wall Mapping (orientation sweep at boot) ---
MAPPER_SWEEP_SPEED = 0.3
MAPPER_SWEEP_DEG_STEP = 10
MAPPER_SONAR_SAMPLES = 3
MAPPER_BLIND_ZONE_CM = 20
MAPPER_BLIND_REVERSE_CM = 40
MAPPER_TOGGLE = True
MAPPER_MIN_SPAN_DEG = 15              # minimum angular span for a wall plateau

# --- EKF Localizer ---
EKF_PROCESS_NOISE_XY = 10.0
EKF_PROCESS_NOISE_THETA = 0.05
EKF_SONAR_NOISE_CM2 = 4.0
EKF_INNOVATION_GATE_CM = 80.0
EKF_LOST_COUNT_MAX = 20
EKF_X_CORRECTION_INTERVAL_S = 30.0


